version: '3.8'

services:
  # PostgreSQL + TimescaleDB 数据库
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: stockschool_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-stockschool}
      POSTGRES_USER: ${POSTGRES_USER:-stockschool}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-stockschool123}
      TIMESCALEDB_TELEMETRY: off
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - stockschool_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-stockschool} -d ${POSTGRES_DB:-stockschool}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # 测试数据库 (独立的PostgreSQL实例)
  test_db:
    image: timescale/timescaledb:latest-pg15
    container_name: stockschool_test_db
    environment:
      POSTGRES_DB: ${TEST_POSTGRES_DB:-stockschool_test}
      POSTGRES_USER: ${TEST_POSTGRES_USER:-stockschool_test}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD:-test123}
      TIMESCALEDB_TELEMETRY: off
    ports:
      - "15433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
      - ./database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - stockschool_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_POSTGRES_USER:-stockschool_test} -d ${TEST_POSTGRES_DB:-stockschool_test}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: stockschool_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - stockschool_network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local
  test_postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  stockschool_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16