# Logstash主配置
node.name: stockschool-logstash
path.data: /usr/share/logstash/data
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs

# 管道配置
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# 监控配置
monitoring.enabled: true
monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# 日志配置
log.level: info
log.format: json

# 其他配置
config.reload.automatic: true
config.reload.interval: 3s
dead_letter_queue.enable: true