# 因子计算配置文件
# 支持配置驱动的因子计算参数管理

# 技术因子配置
technical:
  enabled: true
  max_periods: 500  # 最大计算周期数
  
  # 动量因子
  momentum:
    enabled: true
    periods: [5, 10, 20]  # 动量计算周期
    rsi_period: 14        # RSI周期
    williams_period: 14   # 威廉指标周期
  
  # 趋势因子
  trend:
    enabled: true
    sma_periods: [5, 10, 20, 60]  # 简单移动平均周期
    ema_periods: [12, 26]         # 指数移动平均周期
    macd_fast: 12                 # MACD快线周期
    macd_slow: 26                 # MACD慢线周期
    macd_signal: 9                # MACD信号线周期
  
  # 波动率因子
  volatility:
    enabled: true
    periods: [5, 20, 60]  # 波动率计算周期
    atr_period: 14        # ATR周期
    bb_period: 20         # 布林带周期
    bb_std: 2             # 布林带标准差倍数
  
  # 成交量因子
  volume:
    enabled: true
    sma_periods: [5, 20]  # 成交量移动平均周期
    mfi_period: 14        # 资金流量指标周期

# 基本面因子配置
fundamental:
  enabled: true
  
  # 盈利能力因子
  profitability:
    enabled: true
    metrics:
      - roe           # 净资产收益率
      - roa           # 总资产收益率
      - roic          # 投入资本回报率
      - gross_margin  # 毛利率
      - net_margin    # 净利率
  
  # 估值因子
  valuation:
    enabled: true
    metrics:
      - pe_ttm      # 市盈率TTM
      - pb          # 市净率
      - ps_ttm      # 市销率TTM
      - pcf_ttm     # 市现率TTM
      - ev_ebitda   # EV/EBITDA
      - peg         # PEG比率
  
  # 成长能力因子
  growth:
    enabled: true
    metrics:
      - revenue_yoy     # 营收同比增长率
      - net_profit_yoy  # 净利润同比增长率
    periods: [1, 3, 5]  # 成长性分析年数
  
  # 财务质量因子
  quality:
    enabled: true
    metrics:
      - debt_to_equity  # 资产负债率
      - current_ratio   # 流动比率
      - quick_ratio     # 速动比率

# 情感因子配置（暂时禁用）
sentiment:
  enabled: false
  
  # 新闻情感
  news:
    enabled: false
    sources:
      - sina
      - eastmoney
    sentiment_model: bert
  
  # 社交媒体情感
  social:
    enabled: false
    platforms:
      - weibo
      - xueqiu

# 性能配置
performance:
  parallel_processing: true  # 启用并行处理
  max_workers: 4            # 最大并发数
  batch_size: 100           # 批处理大小
  cache_enabled: true       # 启用缓存
  cache_ttl: 3600          # 缓存时间（秒）

# 数据库配置
database:
  batch_insert: true        # 启用批量插入
  batch_size: 1000         # 批量插入大小
  connection_pool_size: 10  # 连接池大小
  max_overflow: 20         # 最大溢出连接数

# 日志配置
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true
  file_path: "logs/factor_engine.log"
  max_file_size: "10MB"
  backup_count: 5

# 因子计算策略配置
strategy:
  # 数据质量检查
  data_quality:
    min_data_points: 30      # 最少数据点数
    max_missing_ratio: 0.2   # 最大缺失比例
    outlier_detection: true  # 启用异常值检测
    outlier_method: "iqr"    # 异常值检测方法
  
  # 因子标准化
  normalization:
    enabled: true
    method: "zscore"         # 标准化方法: zscore, minmax, robust
    winsorize: true          # 启用缩尾处理
    winsorize_limits: [0.01, 0.99]  # 缩尾限制
  
  # 因子筛选
  factor_selection:
    correlation_threshold: 0.8  # 相关性阈值
    ic_threshold: 0.05         # IC阈值
    coverage_threshold: 0.8     # 覆盖率阈值

# 监控配置
monitoring:
  enabled: true
  metrics:
    - calculation_time    # 计算时间
    - success_rate       # 成功率
    - data_coverage      # 数据覆盖率
    - factor_distribution # 因子分布
  
  alerts:
    enabled: true
    email_enabled: false
    webhook_enabled: false
    thresholds:
      success_rate_min: 0.9
      calculation_time_max: 300  # 秒
      data_coverage_min: 0.8