# 第二阶段优化配置
# 生产环境性能优化和监控增强配置

optimization:
  version: "2.0.0"
  phase: "stage2_optimization"
  
# 性能优化配置
performance:
  # 并行计算配置
  parallel:
    enabled: true
    max_workers: "auto"  # auto: CPU核心数*2
    chunk_size: 100
    memory_threshold: 80  # 内存使用率阈值(%)
    cpu_threshold: 90     # CPU使用率阈值(%)
    
  # 缓存配置
  cache:
    enabled: true
    levels:
      - type: "memory"
        size: 1000
        ttl: 1800
      - type: "redis"
        host: "localhost"
        port: 6379
        ttl: 7200
    
  # 批处理优化
  batch:
    enabled: true
    batch_size: 500
    max_retries: 3
    retry_delay: 5
    
  # 内存管理
  memory:
    gc_threshold: 1000  # 垃圾回收阈值(MB)
    max_memory_usage: 80  # 最大内存使用率(%)
    cleanup_interval: 300  # 清理间隔(秒)

# 监控增强配置
monitoring:
  # 性能监控
  performance:
    enabled: true
    metrics_interval: 60  # 指标收集间隔(秒)
    detailed_logging: true
    
  # 数据质量监控
  data_quality:
    enabled: true
    check_interval: 3600  # 检查间隔(秒)
    sample_size: 100
    
  # 告警配置
  alerts:
    enabled: true
    channels:
      - type: "email"
        smtp_server: "smtp.example.com"
        recipients: ["admin@example.com"]
      - type: "webhook"
        url: "https://hooks.slack.com/services/..."
    
    thresholds:
      error_rate: 5.0      # 错误率阈值(%)
      latency: 10.0        # 延迟阈值(秒)
      memory_usage: 85.0   # 内存使用率阈值(%)
      cpu_usage: 95.0      # CPU使用率阈值(%)

# 部署优化配置
deployment:
  # 容器化配置
  docker:
    enabled: true
    compose_file: "docker-compose.stage2.yml"
    
  # 负载均衡
  load_balancer:
    enabled: true
    type: "nginx"
    upstream_servers: 3
    
  # 自动扩展
  auto_scaling:
    enabled: true
    min_instances: 2
    max_instances: 10
    scale_up_threshold: 80
    scale_down_threshold: 20

# 数据库优化
database:
  # 连接池优化
  connection_pool:
    max_connections: 100
    min_connections: 10
    connection_timeout: 30
    
  # 索引优化
  indexes:
    enabled: true
    auto_create: true
    
  # 分区策略
  partitioning:
    enabled: true
    strategy: "time_based"
    partition_size: "monthly"

# 日志优化
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  rotation:
    max_size: "100MB"
    backup_count: 10
  
  # 结构化日志
  structured:
    enabled: true
    format: "json"
    fields:
      - "timestamp"
      - "level"
      - "module"
      - "function"
      - "execution_time"
      - "memory_usage"

# 测试和验证
testing:
  # 性能测试
  performance:
    enabled: true
    load_test:
      concurrent_users: 100
      duration: 300
    
  # 回归测试
  regression:
    enabled: true
    test_cases: 1000
    
  # 压力测试
  stress:
    enabled: true
    max_load: 10000
    duration: 1800

# 健康检查
health_check:
  enabled: true
  interval: 30
  timeout: 10
  endpoints:
    - "/health"
    - "/metrics"
    - "/api/status"